### ISSUE TITLE
No 'ports' tab

### ISSUE THREAD

**Issue by Drugoy** [emikulic/darkstat#17]
In <a href="http://www.linuxfocus.org/English/September2004/article346.shtml">this</a> article there are screenshots of darkstat's web interface (but of an older version) having tabs like 'ports' and 'protocols':
<img src="http://www.linuxfocus.org/common/images2/article346/darkstat-main.png">

But when I run darkstat (3.0.719 using libpcap version 1.10.0 (with TPACKET_V3)) - its web interface completely lacks those tabs!
I've read man page and there seems to be no options related to that.

Please, help: is it some bug?
Or was this functionality removed between versions 2.6 and 3.0.719?

**Comment by emikulic** [comment]
In v3, ports and protocols are per-host. Go to the hosts page, click on an IP, and it will show you ports and protocols used by that IP.

**Comment by Drugoy** [comment]
Oh thanks for clarifying that.
I think I might not be alone that didn't understand that hosts were clickable there. Maybe it's better to add a note about that on the page of hosts tab or at least clarify it on the man page.
Thank you for this nice program!
