### ISSUE TITLE
all network bytes not captured

### ISSUE THREAD

**Issue by JustinWebDev** [emikulic/darkstat#19]
Darkstat seems to be missing a lot of the traffic on all hosts.  The numbers don't add up.  E.g.,
- for my Ethernet host, I start with 423,358,237 In, download a 1GB file, end up with 704,737,044 In
- for my Wi-Fi host, I can surf, stream movies, and do a video call for over an hour and the bytes are hardly above 0

From the app description, it should capture all types of network traffic (all protocols), internal and external traffic.  What am I missing?

I have a Type 2 Hypervisor VM with a bridged network adapter running Kali.

**Comment by emikulic** [comment]
1. darkstat (only) sees what tcpdump sees. Does tcpdump see all the traffic you expect?
2. Are the bytes missing from the "graphs" page only? If so, the `-l` flag might need configuring.

**Comment by JustinWebDev** [comment]
I'm concerned with the _hosts_ page.  I don't know about tcpdump.

**Comment by JustinWebDev** [comment]
This is my cmd:  `darkstat -i eth0 -l 192.168.2.0/255.255.255.0 --local-only`

Yes, I see a lot of dropped packets.  This is after a fresh start and doing a download and speedtests: 
```
Measuring for 6 mins, 39 secs, since 2023-03-08 21:01:59 EST-0500.
Seen 530,867,396 bytes, in 414,912 packets. (2,831,536 captured, 2,416,217 dropped)
```

**Comment by emikulic** [comment]
Dropping packets means bytes will be undercounted. darkstat isn't able to keep up with the network. Is it using 100% CPU, e.g. if you look in `top`?

**Comment by emikulic** [comment]
It's strange that it's not showing high CPU usage. I'm not sure what else would cause the packet drops. If you run tcpdump, does it also drop packets?

**Comment by JustinWebDev** [comment]
I started tcpdump then ran a speed test.  It did drop packets, but doesn't seem to be at the same rate.
```
74217 packets captured
74941 packets received by filter
724 packets dropped by kernel
```

**Comment by emikulic** [comment]
On the one hand, it's good to know it's not "just" darkstat, but on the other hand it sucks that packets are dropping and it doesn't really help solve the problem. darkstat probably does more work than tcpdump so it misses more packets, but also it's not using 100% of the CPU so it's more like a timing issue than a capacity issue.

Both darkstat and tcpdump use libpcap to get packets, so maybe look there next?

**Comment by emikulic** [comment]
> To be sure, using the above cmd line, darkstat is reporting only traffic exiting or entering the LAN, and not LAN-to-LAN traffic, right?

`-l 192.168.2.0/255.255.255.0` means that 192.168.2.* is treated as "local" so if src is local and dst isn't, that counts as "upload" on the graphs page. If both are local, graphs page doesn't update.

`--local-only` means hosts page only updates if src or dst (or both) are local.

Which means LAN-to-LAN traffic should show up on the hosts page but not the graphs page.

I forgot all this stuff over time, the above is based on reading `acct_for()` in acct.c

**Comment by JustinWebDev** [comment]
I installed Mint on a laptop connected via Ethernet.  Results still don't make sense to me.
sudo darkstat -i eth0 -l 192.168.2.0/255.255.255.0 --local-only

For my desktop:
IN / OUT
9k/10k - start/baseline
11k/50k - after two speedtests
20k/95k - after a 30GB copy from my server (which shows 0/98k)

On the laptop I downloaded a 2GB file from the Internet, and the numbers are only 438M/24M.

For whatever reason, this utility isn't working for me.

**Comment by emikulic** [comment]
Is it still showing dropped packets? If not, hardware offload (I think TCP Segmentation Offload?) can also cause undercounting. Both of these are, unfortunately, limitations of how I capture network traffic and decode it.

**Comment by JustinWebDev** [comment]
Well, during my testing I did not see any dropped packets, but I left the laptop just sit for a day and now I see 5k dropped packets.  TCP segmentation is off.

This is getting beyond me, so I'll have to abandon it.  I appreciate your help.  Thanks.
