### ISSUE TITLE
Default binding port above 1024

### ISSUE THREAD

**Issue by xpaulso** [emikulic/darkstat#22]
I'd like to encourage a default HTTP port to be something above 1024. Essentially an unprivileged port. Maybe 6666?

**Comment by emikulic** [comment]
1. It's very easy to set a port on the commandline.
2. I'm worried the switching cost of changing the default port isn't worth it.
3. Arguably, darkstat is privileged, it starts as root and captures network traffic.

**Comment by xpaulso** [comment]
Number 3 in particular makes sense. I came across port 666 listening on a clients PF Sense firewall and it jump out as something nefarious. Especially on privilege port.  Then notice you had changed it to 667 in git. But since the process is privilege it probably makes sense to keep it. Thanks for the response.
